WebShop/Controllers/CartController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebShop.EF;
using WebShop.Managers;
using WebShop.Models;
using WebShop.Repositories;

namespace WebShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly CartsManager<Cart> _cartsManager;
        private readonly ProductsManager<Product> _productsManager;

        public CartController(ApplicationDbContext context)
        {
            _context = new WorkContext(context);
            _cartsManager = new CartsManager<Cart>(_context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
            _productsManager = new ProductsManager<Product>(_context);
        }

        [HttpPost]
        [Authorize]
        public async Task<JsonResult> AddProduct(string id)
        {
            bool result = false;
            var product = _productsManager.Find(id);
            if (product != null)
            {
                if (!_cartsManager.IsProductInCart(User, product))
                {
                    await _userProfileManager.AddProductToCart(User, product);
                    result = true;
                }
            }

            return Json(result);
        }

        [HttpDelete]
        [Authorize]
        public async Task<JsonResult> RemoveProduct(string id)
        {
            bool result = false;
            var product = _productsManager.Find(id);
            if (product != null)
            {
                if (_cartsManager.IsProductInCart(User, product))
                {
                    await _userProfileManager.RemoveProductFromCart(User, product);
                    result = true;
                }
            }

            return Json(result);
        }

        // GET: Cart/Details
        [HttpGet]
        [Authorize]
        public IActionResult Details()
        {
            var cart = _userProfileManager.GetCartByOwner(User);
            if (cart == null)
            {
                return RedirectToAction(nameof(EmptyCart));
            }

            return View(cart.ProductInCarts.Select(p => p.Product).ToList());
        }

        public IActionResult EmptyCart()
        {
            return View();
        }
    }
}

WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebShop.EF;
using WebShop.Extensions;
using WebShop.Managers;
using WebShop.Models;
using WebShop.Repositories;

namespace WebShop.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly ProductsManager<Product> _productsManager;

        private readonly int ITEMS_ON_PAGE = 6;

        public ProductController(ApplicationDbContext context)
        {
            _context = new WorkContext(context);
            _productsManager = new ProductsManager<Product>(_context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
        }

        // GET: Products
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Products()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult EmptyPage()
        {
            return View();
        }

        // GET: Product/Details/5
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productsManager.Find(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        
        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Title,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.UserProfileId = _userProfileManager.GetUserProfileId(User);
                product.CreatedOn = DateTime.Now;
                await _productsManager.CreateAsync(product);

                return RedirectToAction(nameof(Products));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productsManager.Find(id);
            if (product == null || !_userProfileManager.IsUserOwnProduct(User, product))
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("ProductId,ProductOwnerId,UserProfileId,Title,Description,Price")] Product product)
        {
            if (id != product.ProductId || !_userProfileManager.IsUserOwnProduct(User, product))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _productsManager.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_productsManager.IsProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Products));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _productsManager.Find(id);
            if (product == null || !_userProfileManager.IsUserOwnProduct(User, product))
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var product = _productsManager.Find(id);
            if (product == null || !_userProfileManager.IsUserOwnProduct(User, product))
            {
                return NotFound();
            }
            await _productsManager.RemoveAsync(product);

            return RedirectToAction(nameof(Products));
        }

        private IEnumerable<ProductViewModel> ConvertToViewModel(string userId, IEnumerable<Product> products)
        {
            List<ProductViewModel> productsViewModel = new List<ProductViewModel>();
            var userProfile = _userProfileManager.GetUserProfileById(userId);
            foreach (var item in products)
            {
                productsViewModel.Add(new ProductViewModel
                {
                    ProductId = item.ProductId,
                    Title = item.Title,
                    CreatedOn = item.CreatedOn,
                    Description = item.Description,
                    Price = item.Price,
                    IsInCart = userProfile != null ?
                    userProfile
                    .Cart
                    .ProductInCarts
                    .Any(p => p.ProductId == item.ProductId) : false
                });
            }

            return productsViewModel;
        }

        [HttpGet]
        [AllowAnonymous]
        public PartialViewResult ProductPartial(string sortOrder, string searchString, int? page, bool forOwner, string userId)
        {
            if (searchString != null)
            {
                page = 1;
            }

            IEnumerable<Product> pr;
            if (forOwner)
            {
                if (userId != _userProfileManager.GetUserProfileId(User))
                {
                    throw new Exception("User ids doesn't match");
                }
                pr = _userProfileManager.GetAllProductByOwner(User);
            }
            else
            {
                pr = _productsManager.GetAll();
            }

            var products = ConvertToViewModel(_userProfileManager.GetUserProfileId(User), pr);

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim().ToLower();
                products = products.Where(s => s.Description.ToLower().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "price_desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                case "date_asc":
                    products = products.OrderBy(p => p.CreatedOn);
                    break;
                case "date_desc":
                    products = products.OrderByDescending(p => p.CreatedOn);
                    break;
                default:
                    products = products.OrderBy(p => p.Price);
                    break;
            }

            return PartialView(PaginatedList<ProductViewModel>.Create(products.AsQueryable(), page ?? 1, ITEMS_ON_PAGE));
        }
    }
}

WebShop/Controllers/UserProfileController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebShop.EF;
using WebShop.Models;
using WebShop.Repositories;
using WebShop.Managers;
using WebShop.Models.UserProfileViewModels;
using WebShop.Interfaces;
using System.Linq;

namespace WebShop.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger _logger;
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly IHostingEnvironment _environment;
        private readonly IEmailSender _emailSender;

        public UserProfileController(
              UserManager<ApplicationUser> userManager,
              ILogger<ManageController> logger,
              ApplicationDbContext context,
              IHostingEnvironment environment,
              IEmailSender emailSender)
        {
            _userManager = userManager;
            _logger = logger;
            _context = new WorkContext(context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
            _environment = environment;
            _emailSender = emailSender;
        }

        [TempData]
        public string StatusMessage { get; set; }

        #region Profile managment

        [HttpGet]
        public async Task<IActionResult> ManageUserProfile()
        {
            var user = await _userManager.GetUserAsync(User);
            var userProfile = _userProfileManager.GetUserProfile(User);

            if (userProfile == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var model = new IndexViewModel
            {
                FirstName = userProfile.FirstName,
                SecondName = userProfile.SecondName,
                UserProfileImagePath = userProfile.ImageName,
                DateRegistered = userProfile.DateRegistered
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserProfile(IndexViewModel model, IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var userProfile = _userProfileManager.GetUserProfile(User);
            if (model.FirstName != string.Empty)
            {
                await _userProfileManager.ChangeFirstNameAsync(userProfile, model.FirstName);
            }

            if (model.SecondName != string.Empty)
            {
                await _userProfileManager.ChangeSecondNameAsync(userProfile, model.SecondName);
            }

            if (file != null)
            {
                await _userProfileManager.ChangeUserProfilePhotoAsync(userProfile, file, _environment.WebRootPath);
            }

            StatusMessage = "Your UserProfile has been updated";
            return RedirectToAction(nameof(ManageUserProfile));
        }

        #endregion

        #region Email

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult SendEmail()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SendEmail(string subject, string text)
        {
            var emails = _userProfileManager.GetUserProfiles().Select(p => p.ApplicationUser.Email).ToList();
            await _emailSender.SendEmailAsync(emails, subject, text);

            return RedirectToAction(nameof(ManageUserProfile));
        }

        #endregion
    }
}

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auto Web Shop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/navbar-fixed-side.css" />
        <link rel="stylesheet" href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/navbar-fixed-side.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-2" style="padding-left: 3px;">
                    <nav class="navbar navbar-default navbar-fixed-side">
                        @await Html.PartialAsync("_UserProfileMenuPartial.cshtml")
                    </nav>
                </div>
                <div class="col-sm-9 col-md-9 col-lg-10">
                    <div class="body-content">
                        @RenderBody()
                    </div>
                    <hr />
                    <footer>
                        <p>&copy; 2019 - Auto Web Shop</p>
                    </footer>
                </div>
            </div>
        </div>
    }
    else
    {
        <nav id="header" class="navbar navbar-default navbar-fixed-top">
            <div id="header-container" class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="brand" asp-area="" asp-controller="Home" asp-action="Main" class="navbar-brand">Auto Web Shop</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Main">Home</a></li>
                        <li><a asp-area="" asp-controller="Product" asp-action="Products">Products</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <div id="content-block" class="container body-content content-padding-md">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2019 - Auto Web Shop</p>
            </footer>
        </div>
    }

    @RenderSection("Scripts", required: false)
</body>
</html>

WebShop/Views/Shared/_UserProfileMenuPartial.cshtml
@using WebShop.Extensions.IdentityExtensions

<div class="navbar navbar-default navbar-left">
    <div class="profile-sidebar">
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">
                <p class="small white-text">
                    @User.GetUserName()
                </p>
            </div>
            <h4 style="color:#e7e9fa">@User.GetUserRole() </h4>
        </div>

        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right xs-padding">
            <ul class="nav nav-pills nav-stacked left-side-nav">
                <li class="@UserProfileMenuNavPages.MainNavClass(ViewContext)"><a asp-controller="Home" asp-action="Main"><i class="fa fa-home" style="font-size:18px;color:white"></i> Home</a></li>
                <li class="@UserProfileMenuNavPages.ProductsNavClass(ViewContext)"><a asp-controller="Product" asp-action="Products"><i class="fa fa-car" style="font-size:18px;color:white"></i> Products</a></li>
                <li class="@UserProfileMenuNavPages.CartDetailsNavClass(ViewContext)"><a asp-controller="Cart" asp-action="Details"><i class="fa fa-shopping-cart" style="font-size:18px;color:white"></i> My Cart</a></li>
                <li class="@UserProfileMenuNavPages.ManageAccountNavClass(ViewContext)"><a asp-controller="Manage" asp-action="Index"><i class="fa fa-cog fa-spin" style="font-size:18px;color:white"></i> Manage account</a></li>
                <li class="@UserProfileMenuNavPages.UserProfileNavClass(ViewContext)"><a asp-controller="UserProfile" asp-action="ManageUserProfile"><i class="fa fa-universal-access" style="font-size:18px;color:white"></i> Manage User profile</a></li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="@UserProfileMenuNavPages.SendEmailNavClass(ViewContext)"><a asp-controller="UserProfile" asp-action="SendEmail"><i class="fa fa-envelope" style="font-size:18px;color:white"></i> Send Emails</a></li>
                }
                <li><button type="submit" class="btn btn-success"><i class="fa fa-outdent"></i> Log out</button></li>
            </ul>
        </form>
    </div>
</div>